### ISSUE TITLE
Create DB Schema

### ISSUE THREAD

**Issue by Kropanov** [bemdemsik/telemetry-backend#2]
Use SQLiteStudio or SQLiteFlow or DBeaver (Open-source SQLite Database clients and managers)
When you create the Schema, simply attach screenshot to this issue to close this task.

**Comment by Kropanov** [comment]
main schema entities:
- user (id, firstName, lastName, password, email, access, ...)
- pc (id, name, assembled, ...)
- pc parts (id, name, ...)
...
add additional entities by linking tables:
user -> ps -> ps part ...
------------------------------
Please, create and add main and sub schem entities by example above

**Comment by bemdemsik** [comment]
![Сниамок](https://github.com/bemdemsik/telemetry-backend/assets/130637878/64851636-e57e-4ce5-9e6c-1bd4b61c148a)
![Снимовк](https://github.com/bemdemsik/telemetry-backend/assets/130637878/a1b553be-c2aa-4580-bb64-2a41d5e52d66)
![Снимок](https://github.com/bemdemsik/telemetry-backend/assets/130637878/6b908b5d-ae47-4c33-a8b4-9739fdc5d9c7)

**Comment by Kropanov** [comment]
Not sure, please, update tables!
